/**
 * Portfolio — Main Script (Progressive Enhancement)
 * ────────────────────────────────────────────────
 * Static HTML generated by Eleventy for 100% SEO accessibility.
 * Client-side JS provides instant zero-reload language switching
 * with history.pushState URL updates.
 */

let i18nData = null;
let currentLang = document.documentElement.lang || "fr";

const icons = {
  mail: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>`,
  phone: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>`,
  linkedin: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect width="4" height="12" x="2" y="9"/><circle cx="4" cy="4" r="2"/></svg>`,
  github: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></svg>`,
  download: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>`,
  externalLink: `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" x2="21" y1="14" y2="3"/></svg>`,
  users: `<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>`,
};

/* ═══════════════════════════════════════════════════════════════
   Rendering Helpers (Dynamic Language Swap)
   ═══════════════════════════════════════════════════════════════ */

function updateDOMText(lang) {
  if (!i18nData || !i18nData[lang]) return;

  const t = i18nData[lang];
  const site = i18nData.site;

  // Nav
  const navLinksHtml = `
    <li><a href="#about">${t.nav.about}</a></li>
    <li><a href="#experience">${t.nav.experience}</a></li>
    <li><a href="#projects">${t.nav.projects}</a></li>
    <li><a href="#skills">${t.nav.skills}</a></li>
    <li><a href="#contact">${t.nav.contact}</a></li>
  `;
  const navUl = document.querySelector(".nav__links");
  const mobileUl = document.querySelector(".mobile-menu__links");
  if (navUl) navUl.innerHTML = navLinksHtml;
  if (mobileUl) mobileUl.innerHTML = navLinksHtml;

  // Hero
  const heroGreeting = document.querySelector(".hero__greeting");
  const heroName = document.querySelector(".hero__name");
  const heroHeadline = document.querySelector(".hero__headline");
  const heroStatus = document.querySelector(".hero__status");
  const heroActions = document.querySelector(".hero__actions");

  if (heroGreeting) heroGreeting.textContent = t.hero.greeting;
  if (heroName) heroName.textContent = t.hero.name;
  if (heroHeadline) heroHeadline.textContent = t.hero.headline;
  if (heroStatus) heroStatus.textContent = t.hero.status;

  if (heroActions) {
    heroActions.innerHTML = `
      <a href="mailto:${site.email}" class="btn btn--primary">${icons.mail} ${site.email}</a>
      <a href="tel:${site.phone}" class="btn btn--outline">${icons.phone} ${site.phoneDisplay}</a>
      <a href="${site.linkedin}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.linkedin} ${t.hero.linkedinBtn}</a>
      <a href="${site.github}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.github} ${t.hero.githubBtn}</a>
      ${t.hero.cvUrl ? `<a href="${t.hero.cvUrl}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.download} ${t.hero.cvBtn}</a>` : ""}
    `;
  }

  // About
  const aboutTitle = document.querySelector("#about .section__title");
  const aboutIntro = document.querySelector(".about__intro");
  const educationEl = document.querySelector(".about__education");
  const certsEl = document.querySelector(".about__certifications");

  if (aboutTitle) aboutTitle.textContent = t.about.title;
  if (aboutIntro) aboutIntro.textContent = t.about.intro;

  if (educationEl && t.about.education) {
    educationEl.innerHTML = t.about.education
      .map(
        (edu) => `
      <div class="edu-item fade-in is-visible">
        <div class="edu-item__header">
          <span class="edu-item__institution">${edu.institution}</span>
          <span class="edu-item__location">${edu.location}</span>
        </div>
        <p class="edu-item__degree">${edu.degree}</p>
        <p class="edu-item__period">${edu.period}</p>
        ${edu.description ? `<p class="edu-item__description">${edu.description}</p>` : ""}
      </div>
    `,
      )
      .join("");
  }

  if (certsEl && t.about.certifications) {
    certsEl.innerHTML = t.about.certifications
      .map((c) => {
        const parts = c.split(" : ");
        if (parts.length > 1) {
          return `<p><span class="cert-label">${parts[0]}</span> : ${parts.slice(1).join(" : ")}</p>`;
        }
        const colonParts = c.split(": ");
        if (colonParts.length > 1) {
          return `<p><span class="cert-label">${colonParts[0]}</span>: ${colonParts.slice(1).join(": ")}</p>`;
        }
        return `<p>${c}</p>`;
      })
      .join("");
  }

  // Experience
  const expTitle = document.querySelector("#experience .section__title");
  const expList = document.querySelector(".experience__list");

  if (expTitle) expTitle.textContent = t.experiences.title;
  if (expList && t.experiences.items) {
    expList.innerHTML = t.experiences.items
      .map(
        (exp) => `
      <article class="exp-item fade-in is-visible">
        <div class="exp-item__meta">
          <span class="exp-item__period">${exp.period}</span>
          <span class="exp-item__type">${exp.type}</span>
        </div>
        <div class="exp-item__content">
          <h3 class="exp-item__title">${exp.title}</h3>
          <p class="exp-item__company">${exp.company}</p>
          <p class="exp-item__description">${exp.description}</p>
          <div class="exp-item__tags">
            ${exp.tags.map((tag) => `<span class="tag">${tag}</span>`).join("")}
          </div>
        </div>
      </article>
    `,
      )
      .join("");
  }

  // Projects
  const projTitle = document.querySelector("#projects .section__title");
  const projGrid = document.querySelector(".projects__grid");

  if (projTitle) projTitle.textContent = t.projects.title;
  if (projGrid && t.projects.items) {
    projGrid.innerHTML = t.projects.items
      .map(
        (p) => `
      <a href="/projects/${p.id}/" class="project-card fade-in is-visible" id="project-${p.id}">
        <div class="project-card__thumbnail">
          <img
            src="${p.thumbnail || "/assets/projects/placeholder.png"}"
            alt="Aperçu ${p.name}"
            loading="lazy"
            onerror="this.src='/assets/projects/placeholder.png'"
          />
        </div>
        <div class="project-card__body">
          <div class="project-card__header">
            <span class="project-card__name">${p.name}</span>
            ${p.period ? `<span class="project-card__period">${p.period}</span>` : ""}
          </div>
          <p class="project-card__title">${p.title}</p>
          <p class="project-card__tagline">${p.tagline}</p>
          <div class="project-card__footer">
            ${p.stack.map((s) => `<span class="tag">${s}</span>`).join("")}
          </div>
        </div>
      </a>
    `,
      )
      .join("");
  }

  // Skills
  const skillsTitle = document.querySelector("#skills .section__title");
  const skillsGrid = document.querySelector(".skills__grid");

  if (skillsTitle) skillsTitle.textContent = t.skills.title;
  if (skillsGrid && t.skills.groups) {
    skillsGrid.innerHTML = t.skills.groups
      .map(
        (group) => `
      <div class="skill-group fade-in is-visible">
        <h3 class="skill-group__title">${group.category}</h3>
        <div class="skill-group__items">
          ${group.items.map((item) => `<span class="tag">${item}</span>`).join("")}
        </div>
      </div>
    `,
      )
      .join("");
  }

  // Contact
  const contactTitle = document.querySelector("#contact .section__title");
  const contactText = document.querySelector(".contact__text");
  const contactLinks = document.querySelector(".contact__links");

  if (contactTitle) contactTitle.textContent = t.contact.title;
  if (contactText) contactText.textContent = t.contact.text;
  if (contactLinks) {
    contactLinks.innerHTML = `
      <a href="mailto:${site.email}" class="btn btn--primary">${icons.mail} ${site.email}</a>
      <a href="tel:${site.phone}" class="btn btn--outline">${icons.phone} ${site.phoneDisplay}</a>
      <a href="${site.linkedin}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.linkedin} ${t.contact.linkedinBtn}</a>
      <a href="${site.github}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.github} ${t.contact.githubBtn}</a>
    `;
  }

  // Lang Toggle Button & HTML attributes
  document.documentElement.setAttribute("lang", lang);
  const langBtnText = document.querySelector("#lang-toggle .lang-text");
  if (langBtnText) {
    langBtnText.textContent = lang === "fr" ? "EN" : "FR";
  }

  currentLang = lang;
}

/* ═══════════════════════════════════════════════════════════════
   Language Switcher (Progressive Enhancement)
   ═══════════════════════════════════════════════════════════════ */

function initLangSwitcher() {
  const scriptEl = document.getElementById("i18n-data");
  if (!scriptEl) return;

  try {
    i18nData = JSON.parse(scriptEl.textContent);
  } catch (err) {
    console.error("Failed to parse i18n data", err);
    return;
  }

  const langBtn = document.getElementById("lang-toggle");
  if (!langBtn) return;

  langBtn.addEventListener("click", (e) => {
    e.preventDefault();
    const nextLang = currentLang === "fr" ? "en" : "fr";
    const targetUrl = nextLang === "en" ? "/en/" : "/";

    updateDOMText(nextLang);
    history.pushState({ lang: nextLang }, "", targetUrl);
  });

  window.addEventListener("popstate", (e) => {
    const lang =
      (e.state && e.state.lang) ||
      (location.pathname.startsWith("/en") ? "en" : "fr");
    updateDOMText(lang);
  });
}

/* ═══════════════════════════════════════════════════════════════
   Theme Toggle
   ═══════════════════════════════════════════════════════════════ */

function initTheme() {
  const toggle = document.getElementById("theme-toggle");
  if (!toggle) return;

  const stored = localStorage.getItem("theme");
  const theme = stored || "dark";
  document.documentElement.setAttribute("data-theme", theme);

  toggle.addEventListener("click", () => {
    const current = document.documentElement.getAttribute("data-theme");
    const next = current === "dark" ? "light" : "dark";
    document.documentElement.setAttribute("data-theme", next);
    localStorage.setItem("theme", next);
  });
}

/* ═══════════════════════════════════════════════════════════════
   Mobile Menu
   ═══════════════════════════════════════════════════════════════ */

function initMobileMenu() {
  const burger = document.getElementById("nav-burger");
  const menu = document.getElementById("mobile-menu");
  if (!burger || !menu) return;

  function closeMenu() {
    burger.setAttribute("aria-expanded", "false");
    menu.setAttribute("aria-hidden", "true");
    document.body.style.overflow = "";
  }

  burger.addEventListener("click", () => {
    const isOpen = burger.getAttribute("aria-expanded") === "true";
    if (isOpen) {
      closeMenu();
    } else {
      burger.setAttribute("aria-expanded", "true");
      menu.setAttribute("aria-hidden", "false");
      document.body.style.overflow = "hidden";
    }
  });

  menu.addEventListener("click", (e) => {
    if (e.target.tagName === "A") {
      closeMenu();
    }
  });

  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") closeMenu();
  });
}

/* ═══════════════════════════════════════════════════════════════
   Scroll Fade-In (IntersectionObserver)
   ═══════════════════════════════════════════════════════════════ */

function initScrollFadeIn() {
  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-visible");
          observer.unobserve(entry.target);
        }
      });
    },
    {
      threshold: 0.1,
      rootMargin: "0px 0px -40px 0px",
    },
  );

  document.querySelectorAll(".fade-in").forEach((el) => observer.observe(el));
}

/* ═══════════════════════════════════════════════════════════════
   Init
   ═══════════════════════════════════════════════════════════════ */

document.addEventListener("DOMContentLoaded", () => {
  initTheme();
  initMobileMenu();
  initScrollFadeIn();
  initLangSwitcher();
});

