/**
 * Portfolio — Main Script (Progressive Enhancement)
 * ────────────────────────────────────────────────
 * Static HTML generated by Eleventy for 100% SEO accessibility.
 * Client-side JS provides instant zero-reload language switching
 * with history.pushState URL updates.
 */

let i18nData = null;
let currentLang = document.documentElement.lang || "fr";

const icons = {
  mail: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>`,
  phone: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>`,
  linkedin: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect width="4" height="12" x="2" y="9"/><circle cx="4" cy="4" r="2"/></svg>`,
  github: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></svg>`,
  download: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="btn__icon"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>`,
  copy: `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>`,
};

/* ═══════════════════════════════════════════════════════════════
   Rendering Helpers (Dynamic Language Swap)
   ═══════════════════════════════════════════════════════════════ */

function updateDOMText(lang) {
  if (!i18nData || !i18nData[lang]) return;

  const t = i18nData[lang];
  const site = i18nData.site;

  // Nav
  const navLinksHtml = `
    <li><a href="#about">${t.nav.about}</a></li>
    <li><a href="#experience">${t.nav.experience}</a></li>
    <li><a href="#projects">${t.nav.projects}</a></li>
    <li><a href="#skills">${t.nav.skills}</a></li>
    <li><a href="#contact">${t.nav.contact}</a></li>
  `;
  const navUl = document.querySelector(".nav__links");
  const mobileUl = document.querySelector(".mobile-menu__links");
  if (navUl) navUl.innerHTML = navLinksHtml;
  if (mobileUl) mobileUl.innerHTML = navLinksHtml;

  // Hero
  const heroGreeting = document.querySelector(".hero__greeting");
  const heroName = document.querySelector(".hero__name");
  const heroHeadline = document.querySelector(".hero__headline");
  const heroStatus = document.querySelector(".hero__status");
  const heroActions = document.querySelector(".hero__actions");

  if (heroGreeting) heroGreeting.textContent = t.hero.greeting;
  if (heroName) heroName.textContent = t.hero.name;
  if (heroHeadline) heroHeadline.textContent = t.hero.headline;
  if (heroStatus) heroStatus.textContent = t.hero.status;

  if (heroActions) {
    const mailCopyTitle = lang === "fr" ? "Copier l'email" : "Copy email";
    const phoneCopyTitle = lang === "fr" ? "Copier le numéro" : "Copy phone number";
    heroActions.innerHTML = `
      <div class="btn-group">
        <a href="mailto:${site.email}" class="btn btn--primary">${icons.mail} ${site.email}</a>
        <button class="btn btn--primary btn--copy" data-copy="${site.email}" aria-label="${mailCopyTitle}" title="${mailCopyTitle}" type="button">${icons.copy}</button>
      </div>
      <div class="btn-group">
        <a href="tel:${site.phone}" class="btn btn--outline">${icons.phone} ${site.phoneDisplay}</a>
        <button class="btn btn--outline btn--copy" data-copy="${site.phone}" aria-label="${phoneCopyTitle}" title="${phoneCopyTitle}" type="button">${icons.copy}</button>
      </div>
      <a href="${site.linkedin}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.linkedin} ${t.hero.linkedinBtn}</a>
      <a href="${site.github}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.github} ${t.hero.githubBtn}</a>
      ${t.hero.cvUrl ? `<a href="${t.hero.cvUrl}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.download} ${t.hero.cvBtn}</a>` : ""}
    `;
  }

  // About
  const aboutTitle = document.querySelector("#about .section__title");
  const aboutIntro = document.querySelector(".about__intro");
  const educationEl = document.querySelector(".about__education");
  const certsEl = document.querySelector(".about__certifications");

  if (aboutTitle) aboutTitle.textContent = t.about.title;
  if (aboutIntro) aboutIntro.textContent = t.about.intro;

  if (educationEl && t.about.education) {
    educationEl.innerHTML = t.about.education
      .map(
        (edu) => `
      <div class="edu-item fade-in is-visible">
        <div class="edu-item__header">
          <span class="edu-item__institution">${edu.institution}</span>
          <span class="edu-item__location">${edu.location}</span>
        </div>
        <p class="edu-item__degree">${edu.degree}</p>
        <p class="edu-item__period">${edu.period}</p>
        ${edu.description ? `<p class="edu-item__description">${edu.description}</p>` : ""}
      </div>
    `,
      )
      .join("");
  }

  if (certsEl && t.about.certifications) {
    certsEl.innerHTML = t.about.certifications
      .map((c) => {
        const parts = c.split(" : ");
        if (parts.length > 1) {
          return `<p><span class="cert-label">${parts[0]}</span> : ${parts.slice(1).join(" : ")}</p>`;
        }
        const colonParts = c.split(": ");
        if (colonParts.length > 1) {
          return `<p><span class="cert-label">${colonParts[0]}</span>: ${colonParts.slice(1).join(": ")}</p>`;
        }
        return `<p>${c}</p>`;
      })
      .join("");
  }

  // Experience
  const expTitle = document.querySelector("#experience .section__title");
  const expList = document.querySelector(".experience__list");

  if (expTitle) expTitle.textContent = t.experiences.title;
  if (expList && t.experiences.items) {
    expList.innerHTML = t.experiences.items
      .map(
        (exp) => `
      <article class="exp-item fade-in is-visible">
        <div class="exp-item__meta">
          <span class="exp-item__period">${exp.period}</span>
          <span class="exp-item__type">${exp.type}</span>
        </div>
        <div class="exp-item__content">
          <h3 class="exp-item__title">${exp.title}</h3>
          <p class="exp-item__company">${exp.company}</p>
          <p class="exp-item__description">${exp.description}</p>
          <div class="exp-item__tags">
            ${exp.tags.map((tag) => `<span class="tag">${tag}</span>`).join("")}
          </div>
        </div>
      </article>
    `,
      )
      .join("");
  }

  // Projects
  const projTitle = document.querySelector("#projects .section__title");
  const featuredGrid = document.querySelector(
    ".projects__grid:not(.projects__grid--academic)",
  );
  const academicSubTitle = document.querySelector(".projects__sub-title");
  const academicGrid = document.querySelector(".projects__grid--academic");

  if (projTitle) projTitle.textContent = t.projects.title;

  if (featuredGrid && t.projects.items) {
    const activeTheme =
      document.documentElement.getAttribute("data-theme") || "dark";
    const featuredItems = t.projects.items.filter((p) => p.featured);
    const projectBaseUrl = lang === "en" ? "/en/projects/" : "/projects/";
    featuredGrid.innerHTML = featuredItems
      .map((p) => {
        const darkSrc = p.thumbnail || "/assets/projects/placeholder.webp";
        const lightSrc = p.thumbnailLight || darkSrc;
        const activeSrc = activeTheme === "light" ? lightSrc : darkSrc;
        return `
      <a href="${projectBaseUrl}${p.id}/" class="project-card fade-in is-visible" id="project-${p.id}">
        <div class="project-card__thumbnail">
          <img
            src="${activeSrc}"
            data-src-dark="${darkSrc}"
            data-src-light="${lightSrc}"
            alt="Aperçu ${p.name}"
            loading="lazy"
            onerror="this.src='/assets/projects/placeholder.webp'"
          />
        </div>
        <div class="project-card__body">
          <div class="project-card__header">
            <span class="project-card__name">${p.name}</span>
            ${p.period ? `<span class="project-card__period">${p.period}</span>` : ""}
          </div>
          <p class="project-card__title">${p.title}</p>
          <p class="project-card__tagline">${p.tagline}</p>
          <div class="project-card__footer">
            ${p.stack.map((s) => `<span class="tag">${s}</span>`).join("")}
          </div>
        </div>
      </a>
    `;
      })
      .join("");
  }

  if (academicSubTitle && t.projects.academicTitle) {
    academicSubTitle.textContent = t.projects.academicTitle;
  }

  if (academicGrid && t.projects.items) {
    const academicItems = t.projects.items.filter((p) => !p.featured);
    academicGrid.innerHTML = academicItems
      .map(
        (p) => `
      <div class="project-card project-card--academic fade-in is-visible" id="project-${p.id}">
        <div class="project-card__body">
          <div class="project-card__header">
            <span class="project-card__name">${p.name}</span>
            ${p.period ? `<span class="project-card__period">${p.period}</span>` : ""}
          </div>
          <p class="project-card__title">${p.title}</p>
          <p class="project-card__tagline">${p.tagline}</p>
          <div class="project-card__footer">
            ${p.stack.map((s) => `<span class="tag">${s}</span>`).join("")}
          </div>
        </div>
      </div>
    `,
      )
      .join("");
  }

  // Skills
  const skillsTitle = document.querySelector("#skills .section__title");
  const skillsGrid = document.querySelector(".skills__grid");

  if (skillsTitle) skillsTitle.textContent = t.skills.title;
  if (skillsGrid && t.skills.groups) {
    skillsGrid.innerHTML = t.skills.groups
      .map(
        (group) => `
      <div class="skill-group fade-in is-visible">
        <h3 class="skill-group__title">${group.category}</h3>
        <div class="skill-group__items">
          ${group.items.map((item) => `<span class="tag">${item}</span>`).join("")}
        </div>
      </div>
    `,
      )
      .join("");
  }

  // Contact
  const contactTitle = document.querySelector("#contact .section__title");
  const contactText = document.querySelector(".contact__text");
  const contactLinks = document.querySelector(".contact__links");

  if (contactTitle) contactTitle.textContent = t.contact.title;
  if (contactText) contactText.textContent = t.contact.text;
  if (contactLinks) {
    const mailCopyTitle = lang === "fr" ? "Copier l'email" : "Copy email";
    const phoneCopyTitle = lang === "fr" ? "Copier le numéro" : "Copy phone number";
    contactLinks.innerHTML = `
      <div class="btn-group">
        <a href="mailto:${site.email}" class="btn btn--primary">${icons.mail} ${site.email}</a>
        <button class="btn btn--primary btn--copy" data-copy="${site.email}" aria-label="${mailCopyTitle}" title="${mailCopyTitle}" type="button">${icons.copy}</button>
      </div>
      <div class="btn-group">
        <a href="tel:${site.phone}" class="btn btn--outline">${icons.phone} ${site.phoneDisplay}</a>
        <button class="btn btn--outline btn--copy" data-copy="${site.phone}" aria-label="${phoneCopyTitle}" title="${phoneCopyTitle}" type="button">${icons.copy}</button>
      </div>
      <a href="${site.linkedin}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.linkedin} ${t.contact.linkedinBtn}</a>
      <a href="${site.github}" target="_blank" rel="noopener noreferrer" class="btn btn--outline">${icons.github} ${t.contact.githubBtn}</a>
    `;
  }

  // Lang Toggle Button & HTML attributes
  document.documentElement.setAttribute("lang", lang);
  const langBtnText = document.querySelector("#lang-toggle .lang-text");
  if (langBtnText) {
    langBtnText.textContent = lang === "fr" ? "EN" : "FR";
  }

  currentLang = lang;
}

/* ═══════════════════════════════════════════════════════════════
   Language Switcher (Progressive Enhancement)
   ═══════════════════════════════════════════════════════════════ */

function initLangSwitcher() {
  const scriptEl = document.getElementById("i18n-data");
  if (!scriptEl) return;

  try {
    i18nData = JSON.parse(scriptEl.textContent);
  } catch (err) {
    console.error("Failed to parse i18n data", err);
    return;
  }

  const langBtn = document.getElementById("lang-toggle");
  if (!langBtn) return;

  langBtn.addEventListener("click", (e) => {
    e.preventDefault();
    const nextLang = currentLang === "fr" ? "en" : "fr";
    const targetUrl = nextLang === "en" ? "/en/" : "/";

    updateDOMText(nextLang);
    history.pushState({ lang: nextLang }, "", targetUrl);
  });

  window.addEventListener("popstate", (e) => {
    const lang =
      (e.state && e.state.lang) ||
      (location.pathname.startsWith("/en") ? "en" : "fr");
    updateDOMText(lang);
  });
}

/* ═══════════════════════════════════════════════════════════════
   Theme Toggle
   ═══════════════════════════════════════════════════════════════ */

function updateThemeThumbnails(theme) {
  document.querySelectorAll("img[data-src-light]").forEach((img) => {
    const darkSrc = img.getAttribute("data-src-dark");
    const lightSrc = img.getAttribute("data-src-light");
    if (theme === "light" && lightSrc) {
      img.src = lightSrc;
    } else if (darkSrc) {
      img.src = darkSrc;
    }
  });
}

function initTheme() {
  const toggle = document.getElementById("theme-toggle");
  const stored = localStorage.getItem("theme");
  const theme = stored || "dark";
  document.documentElement.setAttribute("data-theme", theme);
  updateThemeThumbnails(theme);

  if (!toggle) return;

  toggle.addEventListener("click", () => {
    const current = document.documentElement.getAttribute("data-theme");
    const next = current === "dark" ? "light" : "dark";
    document.documentElement.setAttribute("data-theme", next);
    localStorage.setItem("theme", next);
    updateThemeThumbnails(next);
  });
}

/* ═══════════════════════════════════════════════════════════════
   Mobile Menu
   ═══════════════════════════════════════════════════════════════ */

function initMobileMenu() {
  const burger = document.getElementById("nav-burger");
  const menu = document.getElementById("mobile-menu");
  if (!burger || !menu) return;

  function closeMenu() {
    burger.setAttribute("aria-expanded", "false");
    menu.setAttribute("aria-hidden", "true");
    document.body.style.overflow = "";
  }

  burger.addEventListener("click", () => {
    const isOpen = burger.getAttribute("aria-expanded") === "true";
    if (isOpen) {
      closeMenu();
    } else {
      burger.setAttribute("aria-expanded", "true");
      menu.setAttribute("aria-hidden", "false");
      document.body.style.overflow = "hidden";
    }
  });

  menu.addEventListener("click", (e) => {
    if (e.target.tagName === "A") {
      closeMenu();
    }
  });

  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") closeMenu();
  });
}

/* ═══════════════════════════════════════════════════════════════
   Back to Top Button
   ═══════════════════════════════════════════════════════════════ */

function initBackToTop() {
  const btn = document.getElementById("back-to-top");
  if (!btn) return;

  function onScroll() {
    if (window.scrollY > 300) {
      btn.classList.add("is-visible");
    } else {
      btn.classList.remove("is-visible");
    }
  }

  window.addEventListener("scroll", onScroll, { passive: true });
  onScroll();

  btn.addEventListener("click", () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  });
}

/* ═══════════════════════════════════════════════════════════════
   Scroll Reading Progress Bar
   ═══════════════════════════════════════════════════════════════ */

function initScrollProgress() {
  const progressEl = document.getElementById("scroll-progress");
  if (!progressEl) return;

  function updateProgress() {
    const totalHeight =
      document.documentElement.scrollHeight - window.innerHeight;
    if (totalHeight <= 0) {
      progressEl.style.width = "0%";
      return;
    }
    const percent = Math.min(
      100,
      Math.max(0, (window.scrollY / totalHeight) * 100),
    );
    progressEl.style.width = `${percent}%`;
  }

  window.addEventListener("scroll", updateProgress, { passive: true });
  window.addEventListener("resize", updateProgress, { passive: true });
  updateProgress();
}

/* ═══════════════════════════════════════════════════════════════
   ScrollSpy & Nav Elevation
   ═══════════════════════════════════════════════════════════════ */

function initNavScrollSpy() {
  const nav = document.getElementById("nav");
  const navLinks = document.querySelectorAll(
    ".nav__links a, .mobile-menu__links a",
  );
  const sections = document.querySelectorAll("section[id]");

  if (!sections.length) return;

  function handleNavState() {
    // Nav elevation shadow
    if (nav) {
      if (window.scrollY > 20) {
        nav.classList.add("is-scrolled");
      } else {
        nav.classList.remove("is-scrolled");
      }
    }

    // Active section detection
    let currentSectionId = "";
    const scrollPosition = window.scrollY + 120;

    sections.forEach((section) => {
      const sectionTop = section.offsetTop;
      const sectionHeight = section.offsetHeight;

      if (
        scrollPosition >= sectionTop &&
        scrollPosition < sectionTop + sectionHeight
      ) {
        currentSectionId = section.getAttribute("id");
      }
    });

    // Fallback if at the very bottom
    if (
      window.innerHeight + window.scrollY >=
      document.documentElement.scrollHeight - 50
    ) {
      const lastSection = sections[sections.length - 1];
      if (lastSection) currentSectionId = lastSection.getAttribute("id");
    }

    navLinks.forEach((link) => {
      const href = link.getAttribute("href");
      if (href === `#${currentSectionId}`) {
        link.classList.add("is-active");
      } else {
        link.classList.remove("is-active");
      }
    });
  }

  window.addEventListener("scroll", handleNavState, { passive: true });
  handleNavState();
}

/* ═══════════════════════════════════════════════════════════════
   Toast Notifications & Quick Contact Copy
   ═══════════════════════════════════════════════════════════════ */

function showToast(message) {
  let container = document.getElementById("toast-container");
  if (!container) {
    container = document.createElement("div");
    container.id = "toast-container";
    container.className = "toast-container";
    document.body.appendChild(container);
  }

  const toast = document.createElement("div");
  toast.className = "toast";
  toast.innerHTML = `
    <svg class="toast__icon" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
      <polyline points="22 4 12 14.01 9 11.01"></polyline>
    </svg>
    <span>${message}</span>
  `;

  container.appendChild(toast);

  requestAnimationFrame(() => {
    toast.classList.add("is-visible");
  });

  setTimeout(() => {
    toast.classList.remove("is-visible");
    toast.addEventListener("transitionend", () => {
      toast.remove();
    });
  }, 2800);
}

function initContactCopy() {
  document.addEventListener("click", (e) => {
    const copyBtn = e.target.closest("[data-copy]");
    if (!copyBtn) return;

    e.preventDefault();
    e.stopPropagation();

    const valToCopy = copyBtn.getAttribute("data-copy");
    if (!valToCopy) return;

    const isMail = valToCopy.includes("@");

    if (navigator.clipboard) {
      navigator.clipboard
        .writeText(valToCopy)
        .then(() => {
          const lang = currentLang || "fr";
          const msg = isMail
            ? lang === "fr"
              ? `Email copié : ${valToCopy}`
              : `Email copied: ${valToCopy}`
            : lang === "fr"
              ? `Téléphone copié : ${valToCopy}`
              : `Phone copied: ${valToCopy}`;
          showToast(msg);
        })
        .catch(() => {});
    }
  });
}

/* ═══════════════════════════════════════════════════════════════
   Skill Tag Highlighting & Filtering
   ═══════════════════════════════════════════════════════════════ */

function initSkillTagHighlighting() {
  let activeTag = null;

  document.addEventListener("click", (e) => {
    const tag = e.target.closest(".tag");
    const isInsideNavOrHero = e.target.closest(
      ".nav, .hero__actions, .project-back-link",
    );

    if (!tag || isInsideNavOrHero) {
      if (activeTag && !e.target.closest(".tag")) {
        resetSkillFilter();
        activeTag = null;
      }
      return;
    }

    const tagText = tag.textContent.trim().toLowerCase();

    if (activeTag === tagText) {
      resetSkillFilter();
      activeTag = null;
    } else {
      activeTag = tagText;
      applySkillFilter(tagText);
    }
  });

  function applySkillFilter(skillName) {
    const allTags = document.querySelectorAll(".tag");
    const projectCards = document.querySelectorAll(".project-card");
    const expItems = document.querySelectorAll(".exp-item");

    allTags.forEach((t) => {
      if (t.textContent.trim().toLowerCase() === skillName) {
        t.classList.add("is-active");
      } else {
        t.classList.remove("is-active");
      }
    });

    projectCards.forEach((card) => {
      const cardTags = Array.from(card.querySelectorAll(".tag")).map((t) =>
        t.textContent.trim().toLowerCase(),
      );
      if (cardTags.includes(skillName)) {
        card.classList.add("is-highlighted");
        card.classList.remove("is-dimmed");
      } else {
        card.classList.remove("is-highlighted");
        card.classList.add("is-dimmed");
      }
    });

    expItems.forEach((exp) => {
      const expTags = Array.from(exp.querySelectorAll(".tag")).map((t) =>
        t.textContent.trim().toLowerCase(),
      );
      if (expTags.includes(skillName)) {
        exp.classList.add("is-highlighted");
        exp.classList.remove("is-dimmed");
      } else {
        exp.classList.remove("is-highlighted");
        exp.classList.add("is-dimmed");
      }
    });
  }

  function resetSkillFilter() {
    document.querySelectorAll(".tag").forEach((t) =>
      t.classList.remove("is-active"),
    );
    document.querySelectorAll(".project-card, .exp-item").forEach((el) => {
      el.classList.remove("is-dimmed", "is-highlighted");
    });
  }
}

/* ═══════════════════════════════════════════════════════════════
   Init
   ═══════════════════════════════════════════════════════════════ */

document.addEventListener("DOMContentLoaded", () => {
  initTheme();
  initMobileMenu();
  initLangSwitcher();
  initBackToTop();
  initScrollProgress();
  initNavScrollSpy();
  initContactCopy();
  initSkillTagHighlighting();
});

