name: Compile CV

on:
  push:
    branches-ignore:
      - main
    paths:
      - "cv/cv-talvin-ackbaraly.tex"
      - ".github/workflows/compile-cv.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv/*.tex
          latexmk_use_lualatex: false
          args: -pdf -interaction=nonstopmode -halt-on-error

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-talvin-ackbaraly-pdfs
          path: "*.pdf"
          retention-days: 7

      - name: Move PDF to assets/
        run: |
          mkdir -p assets
          mv *.pdf assets/

      - name: Commit and push PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update compiled CVs"
          file_pattern: "assets/*.pdf"
